apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-volume
  labels:
    name: media-volume
spec:
  capacity:
    storage: 1.84Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ubuntu/k8s/media/