apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plex
  name: plex
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostNetwork: true
      containers:
      - image: linuxserver/plex:version-1.21.4.4079-1b7748a7b
        name: plex-media-server
        ports:
        - containerPort: 32469
          protocol: TCP
        - containerPort: 32400
          protocol: TCP
        - containerPort: 8324
          protocol: TCP
        - containerPort: 3005
          protocol: TCP
        - containerPort: 1900
          protocol: UDP
        - containerPort: 5353
          protocol: UDP
        - containerPort: 32410
          protocol: UDP
        - containerPort: 32412
          protocol: UDP
        - containerPort: 32413
          protocol: UDP
        - containerPort: 32414
          protocol: UDP
        env:
        - name: TZ
          value: "America/Los_Angeles"
        - name: VERSION
          value: "docker"
        - name: PLEX_CLAIM
          valueFrom:
            secretKeyRef:
              name: plex-secret
              key: claim-token
        readinessProbe:
          httpGet:
            path: /identity
            port: 32400
          initialDelaySeconds: 15
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /identity
            port: 32400
          initialDelaySeconds: 10
          timeoutSeconds: 10
        volumeMounts:
          - name: plex-volume
            subPath: config
            mountPath: /config
          - name: media-volume
            mountPath: /media
      volumes:
        - name: plex-volume
          persistentVolumeClaim:
            claimName: plex-server-claim
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-claim
