apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: plex-ingress
spec:
  rules:
  - host: "plex.tarbahome.me"
    http:
      paths:
        - backend:
            serviceName: plex-service
            servicePort: pms