apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-server-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: "plex-server-volume"