apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-server-volume
  labels:
    name: plex-server-volume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ubuntu/k8s/plex
