apiVersion: v1
kind: Service
metadata:
  labels:
    app: plex-service
  name: plex-service
spec:
  ports:
  - name: pms
    port: 32400
    targetPort: 32400
    protocol: TCP
  - name: dlna
    port: 32469
    targetPort: 32469
    protocol: TCP
  - name: dlna-udp
    port: 1900
    targetPort: 1900
    protocol: UDP
  - name: bonjour-discovery
    port: 5353
    targetPort: 5353
    protocol: UDP
  selector:
    app: plex
  type: NodePort
