apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-browser-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: "file-browser-volume"