apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-browser-volume
  labels:
    name: file-browser-volume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ubuntu/k8s/file-browser
